#85“）5$85$cgiugitxjgzhfxupcutxxkyxiyxigxgixjgxjgxjtxitxitxitxitxjyxigxihciydiydiydixgxusursutxuifitzizitddixxygxxxiixxiittxiysyiiyyiiyiydyyiddidttdiyfoyditdtydyiyydgzgxuhzfxtitdtidtxixytiziixyoxodiyditxitdxutixtgcrzcxutityifyigitxititxtsiursxyihkkxogxgxkgxyxiyxitxitfuutxigxitxigxjgxjgxjgcjgxjgxjgxjgxgxgxjfzdhzhrhfzjjzjzztzjgtjtijtzfzzzfhzzzuhzzfzdufxufufuuddufkydititdijtjgjfjgzjtxutjtxitxjyxjgxjgxiyx如特殊津贴第一梯队语言态度t rufujvnxv
sleep 1
while true
do
sleep 0.001
set +x
let "j=j+1"
echo "\033[32;;1m我己入侵手机!!!!!!$j \033[49;;1m"
done